### ISSUE TITLE
[Discussion]: Discuss exclusion of `io_sc_set()` from `sinsp_state_sc_set()` default sinsp state enforcement for Falco consumer

### ISSUE THREAD

**Issue by incertum** [falcosecurity/libs#1043]
**Motivation**

`sinsp_state_sc_set()` returns all sc codes that are tagged with `EF_MODIFIES_STATE`  in the event table, see `scap_get_modifies_state_ppm_sc`. This includes sc codes from the `io_sc_set()` category. However, they are super high volume and we have confidently determined in the Falco consumer that they are not needed for sinsp's state engine.

**Feature**

Introduce option to remove `io_sc_set()` from `sinsp_state_sc_set()` and default to removing them already in the ppm sc API.

**Alternatives**

Patch Falco's syscall selection mechanisms and exclude `io_sc_set()` right after calling `sinsp_state_sc_set()`. This is because otherwise end users are confused when they get a warning that they need to enable these IO syscalls with the `-A` flag, because from their (end user's) perspective they may not have added them to any rules. In addition, this will allow Falco end users to only activate the IO sc code they want without needing to pay the cost of having all of them which can explode the event pipe.

@FedeDP @Andreagit97 @jasondellaluce

**Comment by FedeDP** [comment]
Hi!
Indeed, i think that we might want to add an optional param to `sinsp_state_sc_set()` like `exclude_io` (whose default value is `false`), and then consumers can do whatever they prefer.
It would be ok for Falco to drop them, i think.
I would like to understand which state they modify; this needs a little bit of research in the libsinsp parsers code.

Otherwise, don't forget that consumers can still retrieve the `state_sc_set` and then remove sc codes before using it, too!

**Comment by Andreagit97** [comment]
uhm, I agree that we need to remove these warnings from Falco in some way, it would be bad to suggest the use of `-A` with the default configuration. Unfortunately, these parsers are quite relevant since they update the fdinfo, so if you have a rule without these syscalls but that uses the `fd.name` field you could face stale info :/

**Comment by incertum** [comment]
Could be a worthwhile exercise defining what `state` truly means and what the concrete use cases are for threat detection / Falco consumer. Because most of the code base was originally donated by sysdig and sysdig is a system diagnosis tool, likely defining `state` in a much more detailed way when compared to security monitoring use cases. In addition, while for system diagnosis statistical sampling is fair game it is not for a security monitoring tool and the harsh reality right now looks like we can't trace IO syscalls on busy or even moderately busy servers without dropping lots of events.

**Comment by Andreagit97** [comment]
I think that right now the `EF_MODIFIES_STATE` stands for "hei! I'm an event that is processed by parsers and I modify the theadtable/fdtable in some way". I'm agree that we need to remove them from the Falco set, probably we just need to notify the end users because using the same ruleset they could see a difference between Falco 0.34 and Falco 0.35, filterchecks for example could return stale info

**Comment by incertum** [comment]
Agreed, perhaps before many drops caused the info to be stale anyways? Unfortunate the event pipe is just too high for us to simply process all system calls in real-life production  (for now, we may find new tricks)...

If we can complete some more research before Falco 0.35 to track down the exact network cases where that info could be stale that would be ideal, e.g. was reading datagram in some comments so there is going to be more subtle distinctions ...

**Comment by Andreagit97** [comment]
Right now these are the possible issues that I found:
1. Some previous events are dropped, like `connect`, and we cannot refresh the `fdinfo` with `sendto`, `recvfrom`,ecc...
2. We could have `fdinfo` without the tuple (in UDP connections for example) right now we directly populate the tuple with `sendto`, `recvfrom`,ecc...
3. We are sending to a server through a local interface but at a certain point in time another interface becomes the best route available, without  `sendto`, `recvfrom`, ... we are not able to update the local IP

**Comment by incertum** [comment]
Marking as resolved for now, it will be a longer term effort to fully address these. We can reopen the ticket when that time comes or create a new one.
