### ISSUE TITLE
filterchecks.cpp with assertion uinfo != _null failed error

### ISSUE THREAD

**Issue by NitroCao** [falcosecurity/libs#19]
**Describe the bug**
After running `falco` command for a while, it aborts and outputs:
```
falco: /home/nitroc/falco/build/sysdig-repo/sysdig-prefix/src/sysdig/userspace/libsinsp/filterchecks.cpp:4617: virtual uint8_t* sinsp_filter_check_user::extract(sinsp_evt*, uint32_t*, bool): Assertion `uinfo != __null' failed.
```

**How to reproduce it**

Follow the `Getting Started` guide and build Falco from source code.

**Expected behaviour**

Run as normal without abortion.

**Screenshots**

![image](https://user-images.githubusercontent.com/17915615/110955185-49158180-8384-11eb-9112-1e8fd4254cc4.png)

**Environment**

- Falco version:

```
Falco version: 0.27.0
Driver version: 5c0b863ddade7a45568c0ac97d037422c9efb750
```
- Build Params:
```
-DBUILD_BPF=ON -DCMAKE_BUILD_TYPE=Debug
```
- System info:

![image](https://user-images.githubusercontent.com/17915615/110955604-baedcb00-8384-11eb-966f-1e72fd715123.png)
- Cloud provider or hardware configuration:
- OS: Latest Arch Linux

- Kernel: 5.4.84-1-lts

- Installation method: from source

**Additional context**

**Comment by NitroCao** [comment]
Hi guys, any progress on this? I compiled sysdig from the source code and ran it successfully, which last commit is fd59f0e75c6d10a9f53a50c067cbbc74e16b6329 on Mar 31. Hope this message is useful.

**Comment by FedeDP** [comment]
Hi @NitroCao !
I was able to reproduce your issue; it does only appear when building in debug mode, otherwise the assert is not really triggered.
Most probably, some new user is created while falco is running and it has some conditions on usernames; falco does not refresh its users list cache, thus it is not able to find your newly created user and that leads to falco being aborted when built in debug mode.
Again, note that in release mode no abort will be triggered.
