### ISSUE TITLE
sinsp-example inconsistent results

### ISSUE THREAD

**Issue by rcohencyberarmor** [falcosecurity/libs#794]
Hi All,

I'm using the sinsp-example for monitor all syscalls of simple redis container running on k8s (on minikube) and I get inconsistent results. sometimes some syscalls are missing and sometimes all of the syscalls are found , I have compare the sinsp-example result to strace results. I have saw that the syscalls that are missing is called in the redis processes not so often(syscalls like uname, lseek, etc)

0. get list of all syscalls of redis using strace( strace -f -c docker run -it redis &> strace-redis-result-file)
1. compile sinsp-example, and bpf driver
2. run minikube
3. run the sinsp-exampe with the following command:  sudo ./build/libsinsp/examples/sinsp-example -a -b ./build/driver/bpf/probe.o &> to-some-file
4. create simple redis on k8s: kubectl create deploy --image=redis redis and wait for 60 secs
5. filter result in to-some-file with the redis container ID
6. compare filter results with strace results
7. return to 4 stage for let's say 10 times

stage #6 need to be successful for all 10 times 

![image](https://user-images.githubusercontent.com/84019060/207818392-02517044-7516-407d-97e6-24f1c1f84b7a.png)

the list of the syscalls between the attempts are thye missing one

kernel version: 5.15.0-48-generic 
linux distribuion: ~20.04.1-Ubuntu
on the latest falco libs

**Comment by slashben** [comment]
I suspect that the ring buffer overruns here, but it is not clear how should I manage the libs to avoid this.

**Comment by Andreagit97** [comment]
yeah looking at the issue it seems like in some runs you faced some event drops, buffers are full and you miss some events. 
If you call the example like this, 
```bash
 sudo ./build/libsinsp/examples/sinsp-example -a -b ./build/driver/bpf/probe.o &> to-some-file
```
it is very likely that it will drop since it is printing every single event it sees into your file. Printing something in userspace consumes a lot of userspace time so no one is reading the buffers and they will become full in short time.

So first of all probably you have to use a filter `-f proc.name=<redis-whatever>` and if this shouldn't be enough you can configure bigger buffers with the `-d` option, something like `-d 16777216` will create buffers of 16 MB (`16777216` is the dimension is in bytes)

The libraries offer some other features like the `simple-consumer` approach that allows you to ignore not interesting syscalls for your use case, but they are not implemented in this example, as the name said this is just an example of how to use the libraries, I would avoid to use it in real scenarios or in production.

Hoping this could help you, let me know if you have other doubts :)

**Comment by FedeDP** [comment]
> The libraries offer some other features like the simple-consumer approach that allows you to ignore not interesting syscalls for your use case, but they are not implemented in this example, as the name said this is just an example of how to use the libraries, I would avoid to use it in real scenarios or in production.

I fully agree with Andrea here; we cannot declare an example as production ready :rofl:
