### ISSUE TITLE
Fdinfo is abnormally empty at high tps

### ISSUE THREAD

**Issue by jundizhou** [falcosecurity/libs#901]
**Describe the bug**

When using ab or Jmeter for high Tps pressure testing, I found that some Fd continues to read and write to the network after the close-syscall is successful. The Parse_close_exit clears the Fdinfo, which leads to the failure to get tuple
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/92794317/219563004-77c61447-e8e6-4307-ad44-54618d367ef9.png">

**How to reproduce it**

Use ab to pressure test a url, and we will see that some network system calls are missing fdinfo

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by incertum** [comment]
Hi :wave: @jundizhou this is a super interesting observation. 

Not directly related to this, but perhaps useful for some additional context about what we are up to these days in order to provide some better optimization mechanisms, please see https://github.com/falcosecurity/falco/issues/2433#issuecomment-1447620920

It mentions some high-level aspects about the state engine and we are in the process of re-auditing the parsers, so the issue you bring up here seems to fall into this line of work as well. Would you have new ideas re what we could do differently in order to also support such high stress cases?
